### ISSUE TITLE
The Windows version is not 3.1.5!

### ISSUE THREAD

**Issue by lrineau** [conda-forge/mpfr-feedstock#15]
The Windows version of this package uses the fork from Brian Gladman, with commit https://github.com/BrianGladman/mpfr/blob/1535d223d5df0c8f6a2722796efb96c845c25405.

As one can see in the `NEWS` file, the changes between version 3.1.5 and that intermediate 4.0.0-dev version is rather big:
https://github.com/BrianGladman/mpfr/blob/1535d223d5df0c8f6a2722796efb96c845c25405/NEWS#L23-L89

That makes the package almost unusable in a cross-platform way.

See https://github.com/CGAL/cgal/pull/2808 and the [that compilation error on AppVeyor](https://ci.appveyor.com/project/maxGimeno/cgal/build/job/c39rdcpbt2heyi7p).

Cc @maxGimeno

**Comment by isuruf** [comment]
I tried to fix this in #13, but didn't have time to complete it. Any help is appreciated
