### ISSUE TITLE
MPC issue on Windows after the MPFR 4.1.0 update

### ISSUE THREAD

**Issue by bluescarni** [conda-forge/mpfr-feedstock#32]
I have a strange behaviour to report after the update to MPFR-4.1.0 on Windows. This is about the interaction between MPFR-4.1.0 and the current version of MPC available on conda-forge (1.1.0).

MPC has a function called ``mpc_cmp_abs()``, which starts off like this:

```c
/* return mpfr_cmp (mpc_abs (a), mpc_abs (b)) */
int
mpc_cmp_abs (mpc_srcptr a, mpc_srcptr b)
{
   // a couple of non-essential lines here....

   /* Handle numbers containing one NaN as mpfr_cmp. */
   if (   mpfr_nan_p (mpc_realref (a)) || mpfr_nan_p (mpc_imagref (a))
       || mpfr_nan_p (mpc_realref (b)) || mpfr_nan_p (mpc_imagref (b)))
     {
       mpfr_t nan;
       mpfr_init (nan);
       mpfr_set_nan (nan);
       ret = mpfr_cmp (nan, nan);
       mpfr_clear (nan);
       return ret;
     }

   // .... more code
}
```

``mpc_cmp_abs()`` compares the absolute values of two complex multiprecision numbers ``a`` and ``b``. The snippet above shows that if ``a`` or ``b`` contain NaN in either component, then MPC performs a comparison using the MPFR ``mpfr_cmp()`` function and returns the result.

The problem that I am experiencing is that, on Windows, after the MPFR update from 4.0 to 4.1 it seems like the ``if`` condition

```c
   if (   mpfr_nan_p (mpc_realref (a)) || mpfr_nan_p (mpc_imagref (a))
       || mpfr_nan_p (mpc_realref (b)) || mpfr_nan_p (mpc_imagref (b)))
```

does **not** trigger any more when ``a`` or  ``b`` contain a NaN component. That is, if I invoke the ``mpc_cmp_abs()`` function with NaN arguments, the branch is skipped. Downgrading MPFR to 4.0 fixes the issue, i.e., the ``mpc_cmp_abs()`` function behaves correctly again.

Unfortunately, I could not debug the issue extensively because I don't have access to Windows machines currently. But I was able to verify in an appveyor VM that the ``if`` condition

```c
   if (   mpfr_nan_p (mpc_realref (a)) || mpfr_nan_p (mpc_imagref (a))
       || mpfr_nan_p (mpc_realref (b)) || mpfr_nan_p (mpc_imagref (b)))
```

works correctly if it is compiled while including the MPFR 4.1 headers. Because ``mpfr_nan_p()`` is a macro (and the current MPC package in conda was compiled with the MPFR 4.0 version of this macro), this makes me believe that perhaps something changed in the implementation of the macro or perhaps in the NaN representation. Or at least that is the only explanation that I have for this behaviour.

Sorry for the rambling character of this report but I am a bit at a loss at this point....

**Comment by isuruf** [comment]
Do you have a simple C code that exhibits this behaviour?

**Comment by bluescarni** [comment]
@isuruf 

I managed to compile and test a minimal example on appveyor. Here's the C++ code:

```c++
#include <mpc.h>
#include <mpfr.h>

#include <iostream>

int main()
{
        // Init a and b as NaNs with 64 bits of precision.
        mpc_t a, b;
        mpc_init2(a, 64);
        mpc_init2(b, 64);

        std::cout << "MPFR erange flag before: " << mpfr_erangeflag_p() << '\n';

        mpc_cmp_abs(a, b);

        std::cout << "MPFR erange flag after: " << mpfr_erangeflag_p() << '\n';

        mpc_clear(a);
        mpc_clear(b);
}
```

If you compile this file in an environment containing MPFR 4.0, the output is:

```console
MPFR erange flag before: 0
MPFR erange flag after: 16
```

According to my understanding of the MPFR and MPC docs, this should be the correct result: comparison involving NaNs ends up setting the MPFR erange exception.

If you update MPFR to 4.1, recompile the example and re-run, the output is:

```console
MPFR erange flag before: 0
MPFR erange flag after: 0
```

Which, to my understanding, is not correct.

**Comment by bluescarni** [comment]
Digging more, I am a bit puzzled. It seems like updating MPFR from 4.0 -> 4.1 and then **NOT** recompiling the example, the correct result is produced. I also noticed that in MPFR 4.1, there are 2 DLLs in the package - ``mpfr.dll`` and ``mpfr-6.dll``. Could it be that the erange flag is some sort of  global variable defined in both DLLs, and that binaries linking to the old DLL ``mpfr.dll`` are seeing a different instance of the same global variable defined also in ``mpfr-6.dll``?

**Comment by isuruf** [comment]
Ah, yes. Let me try to fix that issue

**Comment by isuruf** [comment]
Can you check the newest build?

**Comment by bluescarni** [comment]
@isuruf cheers! I am running the CI pipeline on my project, so far it looks fixed :) I'll ping here again once it's fully finished.

**Comment by bluescarni** [comment]
Ok everything looks fixed on my side, thanks a lot for the assistance!

Closing the report.
